org.gradle.parallel=true
org.gradle.workers.max=3
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512M -Dfile.encoding=UTF-8

# Mod properties
mod.version=1.0.1
mod.group=xyz.louiszn
mod.id=offlinemodefix
mod.name=Offline Mode Fix

# Global dependencies
deps.fabric_loader=0.18.4

publish.modrinth=N8eMBhbr
