name: Publish Mod
on:
  push:
    tags:
      - 'v*' # Triggers only when you push a tag like v0.1.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Publish to Modrinth
        run: ./gradlew buildAndCollect publishMods
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: offline-mode-fix-jars
          path: versions/*/build/libs/*.jar
          if-no-files-found: warn